export const EMAILCHANGED = "EMAILCHANGED"
export const PASSWORDCHANGED = "PASSWORDCHANGED"
export const USERNAMECHANGED = "PASSWORDCHANGED"
export const PHONECHANGED = "PASSWORDCHANGED"
export const DATEOFBIRTHDAYCHANGED = "PASSWORDCHANGED"


export const ADDTOCART = 'ADDTOCART';
export const REMOVEFROMCART = 'REMOVEFROMCART';
export const INCREMENTCART = 'INCREMENTCART';
export const DECREMENTCART = 'DECREMENTCART';
export const INCREMENTHEADCART = 'INCREMENHEADTCART';
export const DECREMENTHEADCART = 'DECREMENTCARHEADT';


