export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';

export const LOGINSUCCESS = 'LOGINSUCCESS';
export const LOGINFAILED = 'LOGINFAILED';
export const REGISTERSUCCESS = 'REGISTERSUCCESS';
export const REGISTERFAILED = 'REGISTERFAILED';

export const GETMENU = 'GETMENU';

export const NEWADDRESS = 'NEWADDRESS';
export const GETADDRESS = 'GETADDRESS';
export const DELETEADDRESS = 'DELETEADDRESS';

export const GETBRANCHES = 'GETBRANCHES';

export const GETOFFERS = 'GETOFFERS';
export const GETOFFERSMENU = 'GETOFFERSMENU';

export const ADDTOCART = 'ADDTOCART';
export const REMOVEFROMCART = 'REMOVEFROMCART';
export const INCREMENTCART = 'INCREMENTCART';
export const DECREMENTCART = 'DECREMENTCART'; 

